version: '2'

services:
  
  mysql:
    build: ./bancos/mysql/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: default
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./bancos/mysql/data:/var/lib/mysql
  postgres:
    build: ./bancos/postgresql/.
    container_name: postgres
    environment: 
      POSTGRES_PASSWORD: root
    ports: 
      - 5432:5432
    volumes:
      - ./bancos/postgresql/data:/var/lib/postgresql/data
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: root 
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      PMA_ARBITRARY: 1

  php:
    build: ./php/.
    container_name: php
    volumes:
      - ./sites:/var/www/html
    ports:
      - 9000:9000
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes_from:
      - php
    volumes:
      - ./nginx:/etc/nginx/conf.d
    links:
      - php
    ports:
      - 80:80

  angular:
    build: ./angular/.
    container_name: angular
    volumes:
      - ./sites:/home/node
    ports:
      - 4200:4200
    stdin_open: true
    tty: true
      
  phppgadmin:
    build: ./phppgadmin/.
    restart: always
    links: 
      - postgres
    ports:
      - 8081:80
    environment: 
      PHP_PG_ADMIN_SERVER_PG_DUMP_PATH: /usr/bin/pg_dump
      PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH: /usr/bin/pg_dumpall
      PHP_PG_ADMIN_SERVER_HOST: postgres
      
      




    
    