version: '2'

services:
  
  db:
    build: ./bancos/mysql/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: teste
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./bancos/mysql/data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: root 
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
      PMA_ARBITRARY: 1

  php:
    build: ./php/.
    container_name: php
    volumes:
      - ./sites:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes_from:
      - php
    volumes:
      - ./nginx:/etc/nginx/conf.d
    links:
      - php
    ports:
      - 80:80